pest-parser/pest

src/grammar.rs
Hey, found a few typos while the reading the docs.
A few thoughs as well:
- you mention `without making progress` a few times in the grammar but don't explain what you mean by it, does the parsing stop
- you call `parse.exp()` a few times but never say what is it, i guess it's expected? (I like long names)
- does `[""]` match everything?
- when talking about silent rules you say they don't appear in `Parser::queue` or `Parser::expected` . I can imagine what the queue is but not sure about expected
- `// exp is silent since we already know what we're parsing` in the `process` doc. I didn't know, it just says something about nested letter and you see the example only at the end. Also from the point above, I thought silent rules were not added to the stream of token and yet they are there in …
=> Fix some docs + thoughts on the doc

Cargo.toml, src/lib.rs, src/parser.rs, src/parsers/rdp.rs
=> Add queue_with_captures(), similar to queue() except it contains the value

.travis.yml, README.md, src/lib.rs
Also caches cargo in travis
Fix #64 & #70
=> Update readme with install/build/test

examples/calculator.rs
=> Show an example how to use different associativities.

README.md
...to actually make it work ;)
=> Fix parens in first README example

pest/src/inputs/input.rs, pest/src/lib.rs, pest_derive/src/lib.rs
Suggestion for fixing user documentation.
=> User documentation fix

pest/_README.md, pest_derive/_README.md, pest_grammars/_README.md
_README.md symlinks are broken
=> Fix broken-symlinks

.travis.yml
This will improve coverage accuracy and lead to a much faster build. Waiting for [tarpaulin/57](https://github.com/xd009642/tarpaulin/issues/57).
=> Migrated to tarpaulin for coverage.

pest_derive/Cargo.toml, pest_derive/src/lib.rs
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> pest_derive: update syn to 0.11

README.md
=> docs.rs is working again

derive/Cargo.toml, derive/src/generator.rs, derive/src/lib.rs, meta/src/parser.rs, vm/src/lib.rs
This is to address https://github.com/pest-parser/pest/issues/203
=> Upgrading to syn 0.12 and quote 0.4

pest/src/iterators/flat_pairs.rs, pest/src/iterators/pair.rs, pest/src/iterators/pairs.rs, pest/src/iterators/queueable_token.rs, pest/src/iterators/tokens.rs, pest/src/parser_state.rs
This should address https://github.com/pest-parser/pest/issues/205.
=> Implement DoubleEndedIterator for Pairs, FlatPairs, and Tokens

derive/src/generator.rs, derive/src/lib.rs
Closes #215.
I'll need some help writing a test for this. It seems that making a [`Generics`](https://docs.rs/syn/0.13/syn/struct.Generics.html) directly is quite awkward.
=> Fix custom derive for structs with type parameters

derive/src/generator.rs, derive/src/lib.rs, derive/tests/grammar.pest, derive/tests/grammar.rs, meta/src/validator.rs, pest/src/parser_state.rs, pest/src/stack.rs
Addresses issue https://github.com/pest-parser/pest/issues/231.
=> Adding the PEEK_ALL and POP_ALL rules

meta/src/optimizer/restorer.rs
Whoops. Looks like I missed this a while back.
=> Fix small restorer bug

pest/src/stack.rs
The fix for this involves removing the manual book keeping completely.
=> Fixing some bad book keeping on the stack implementation

meta/src/validator.rs
=> Added some validation improvements.

pest/src/error.rs
=> Error with path

codecov.yml, pest/src/position.rs, pest/src/span.rs, pest/tests/calculator.rs
Removed `derive/src/lib.rs` from codecov.
=> Added some tests.

pest/src/iterators/pairs.rs
@Kroc, per out Gitter discussion.
=> Added capturing to Pairs.

README.md
https://github.com/pest-parser/pest/issues/253
The only thing missing is that we need a new benchmark results svg to reflect all the performance changes @dragostis.
=> Update the README to reflect the website changes

README.md
Might be of interest to you or others.
=> Add hexdino to readme

generator/src/generator.rs, generator/src/lib.rs, meta/src/lib.rs, meta/src/optimizer/mod.rs, meta/src/optimizer/restorer.rs, meta/src/optimizer/skipper.rs, meta/src/parser.rs, meta/src/validator.rs, pest/src/error.rs, pest/src/iterators/pairs.rs, pest/src/stack.rs, pest/src/unicode/mod.rs, vm/src/lib.rs
Prerequisite to enabling clippy on CI (#295, #310).
cc @luizdepra (feel free to pull this into #310)
=> Fix clippy errors

pest/src/error.rs
Fixes #307. @sunng87, is this a fine solution?
=> Added Error line/column info.

README.md
pest is a real pleasure to work with by the way :)
=> Add json5-rs to Projects using pest

meta/src/optimizer/mod.rs, meta/src/optimizer/restorer.rs, pest/src/iterators/pairs.rs
Includes #354 (the two changesets would be very conflicting otherwise). Contains the last of the changes removed from #315 for the sake of getting it merged easily (and a cleaner git history). r? @dragostis
=> Test cleanup with box_tree! macro

derive/Cargo.toml, generator/Cargo.toml, vm/Cargo.toml
This allows us to test if our lower bounds are correct
=> travis: add a build with minimum dependencies

derive/src/lib.rs, derive/tests/grammar_inline.rs, generator/src/generator.rs, generator/src/lib.rs
I need inline definitions of grammar files. If there is a better way of doing this, please let me know!
=> add support for inline grammars

README.md
Hello ✋,
First of all, thanks a ton for Pest! This such an awesome project!
I'm working on a small CLI tool to query JSON files/content and it's powered by Pest. I would be super happy if it can be listed in the projects section of the readme 👍.
Thanks!
=> Add jql - A JSON Query Language CLI tool - to the projects using pest

README.md
elastic-rs is a library which converts user input to elasticsearch DSL.
pest is used to parse the boolean expression
Thanks a lot for this elegant parser!
=> add elastic-rs which use pest as parser

pest/src/iterators/flat_pairs.rs, pest/src/iterators/pair.rs, pest/src/iterators/pairs.rs
Fixes #383, Closes #301.
Apparently, the aggressive solution wasn't too bad. I'd done 90% of the work already, just hadn't done the final bit, apparently.
r? @dragostis
=> fix 2.1 regression

meta/Cargo.toml
=> sha-1 is now minimal-versions correct

README.md
We're using pest as well as pest-ast :)
=> Add ZoKrates to list of projects in README

README.md
👋 I recently wrote an interpreter for an esolang called AshPaper that interprets formally constrained poetry as compilable code. I used pest to parse and categorize the input (poetry) into corresponding instructions and it was _such_ a pleasure to work with. 
I'd be honored to make it onto the list of projects that use pest. Thanks for all you do, I love this project!
=> Add AshPaper to the list of projects using pest

.travis.yml
=> Stop fuzz regression stage from running on PRs.

README.md
It's a GraphQL runtime for Rust which is using Pest to parse queries.
=> Add Myoxine.

meta/src/optimizer/concatenator.rs, meta/src/optimizer/factorizer.rs, meta/src/optimizer/restorer.rs, meta/src/optimizer/rotater.rs, meta/src/optimizer/skipper.rs, meta/src/optimizer/unroller.rs, meta/src/parser.rs, pest/src/position.rs
Follow up of #481
Fixes #483
cc @CAD97
=> Fix clippy lints

.github/workflows/ci.yml, derive/src/lib.rs, derive/tests/grammar.rs, generator/src/generator.rs, generator/src/macros.rs, meta/src/lib.rs, meta/src/parser.rs, meta/src/validator.rs, vm/src/macros.rs
This pr attempts to fix the issues encoutnered with the migration of the CI from travis to github actions. The issues that have been solved are:
- Install gcc, libssl-edv and pkg-config to the recipes that needed it.
- Install minimal rust toolchains for nightly, since they don't come with rust-fmt or clippy
- fix all clippy warn
=> fix CI workflows

README.md
This PR adds [Vector](https://vector.dev) to the list of projects using Pest. We're using Pest to power [Timber Remap Language](https://vector.dev/docs/reference/remap), a lean data transformation language for observability event data.
=> Add Vector to projects using Pest

README.md
=> adding new project using pest in readme

README.md
See: https://github.com/mitsuhiko/insta/blob/5702955557d6d576498b723609e0869cf1a5da65/Cargo.toml#L42
=> README: add `insta` crate into projects using pest

.github/workflows/ci.yml
=> Switch from cargo-tarpaulin to cargo-llvm-cov

.github/workflows/ci.yml
fix llvm cov to v0.3.3
fixes #610
=> fix: test coverage execution (fixes #610)

pest/src/error.rs
See #593 
I learned some stuff about branches and accidentally ended up closing the other PR rather than modifying it but that's alright
=> feat: make error line accessible

meta/Cargo.toml
`sha1` is the primary name now.
=> Use new `sha-1` package name

README.md, debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, vm/Cargo.toml
=> doc: add a link to awesome-pest

meta/src/optimizer/mod.rs
I think this can help debugging so that users can know where the error occurs.
=> Implement core::fmt::Display for OptimizedExpr

.github/workflows/ci.yml, debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, generator/src/generator.rs, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, vm/Cargo.toml
and bump versions
fixes #326
see https://github.com/pest-parser/pest/pull/923#issue-1879165223
=> add a comment to EOL
