pest-parser/pest

src/input.rs, src/inputs/string_input.rs, src/parser.rs, src/parsers/rdp.rs, tests/sentence_lifetime.rs
This allows the usage of an in-memory string, without implicit copying during processing.
=> Implement support for references within StringInput

src/input.rs, src/inputs/string_input.rs, src/parser.rs, src/parsers/rdp.rs, tests/sentence_lifetime.rs
Seems the key lifetime symbol is Input slice() -> &str. If we don't specify it, it will use parser's default scope.
=> Adding some lifetime back

README.md
* Fixed links to issues to point to the main repo (these will be wrong if one forks the repo and they don't work as is also)
* Removed a trailing white space on one line.
=> Fixed links to Roadmap issues

README.md
The crates.io versions in the text of the readme is missing the patch component, causing a parsing error (well, not really, just cargo can't find it).
=> Fix small version typo

README.md
I've reworded some parts of the README and expanded the example to clarify what a token pair is and how they can be used.
This is inspired by [this reddit comment](https://www.reddit.com/r/rust/comments/6uho7c/pest_10_beta_procedural_macros_simplified_api/dltdzzt/) asking for a clarification on this. I had the same confusion when I first saw this project, so hopefully this helps.
=> Clarify the example in the README.

pest_derive/src/lib.rs
That makes the dummy `const _GRAMMAR` be present only during development automatically, avoiding cases where one might forget to remove the line, or to simplify contributions / casual hacking, as there's no need to remember to add the line when editing the grammar.
=> Add cfg(debug_assertions) to suggested code

pest/src/inputs/file_input.rs, pest/src/inputs/mod.rs, pest/src/inputs/span.rs, pest/src/inputs/string_input.rs, pest/src/parser.rs, pest/tests/calculator.rs, pest/tests/json.rs
~~Fixes 141~~ 
Added support for `StringInput` to hold a borrowed `str`, as well as `String`. This is to avoid String copy in functions like `parse_str`.
=> Allow StringInput from borrowed str, to avoid copy

pest/src/parser_state.rs
=> fix typo in doc leading to dead links.

pest_derive/src/generator.rs
This is necessary in case the client code redefines `Result` with a type alias.
=> Use fully-qualified path for Result

pest/src/macros.rs
Based on https://elliotekj.com/2017/07/03/handling-optional-trailing-commas-macro_rules/.
Before, this was invalid:
```rust
#[test]
fn parses_to() {
parses_to! {
parser: AbcParser,
input: "abcde",
rule: Rule::a,
tokens: [
a(0, 3, [
b(1, 2),
]),
c(4, 5)
]
};
}
```
I think I understand the `parses_to` macro invocation, but I can't really say that about the `consumes_to` macro, so it would be good if you could really double-check the changes :)
=> Allow trailing comma in macros

README.md
GitHub will render SVGs referenced directly from the repo now! (this was a ridiculous amount of effort; see github/markup#556 if you're morbidly curious.) As a result:
* no need to route through another layer of CDN (i.e. rawgit's)
* because you don't need to specify the commit SHA in the URL, it'll automatically reflect the `pest-logo.svg` and `results.svg` of whatever commit/branch it's being shown on
=> Refer directly to SVGs in repo

pest/src/position.rs
These expressions borrow a reference that is immediately dereferenced
by the compiler.
=> clippy: Fix needless borrow warnings.

pest/src/position.rs
Looks like I made a small mistake here. I forgot to check to ensure that the end of the slice I'm checking is within the bounds of the input.
=> fix a bug with skip_until_any

derive/src/generator.rs
Fixes #218.
Per https://github.com/rust-lang/rust/pull/49291#issuecomment-377682736, `#[inline]` has no effect on lambdas, and rustc has stopped allowing this in nightly.
=> remove #[inline] on lambdas

pest/src/iterators/pair.rs
This matters when using `Tokens`. Without this fix, `pair.into_inner().tokens()` will not iterate the final `End` token.
=> Fix conversion from Pair to Pairs

README.md, grammars/benches/json.rs, pest/src/iterators/pair.rs, pest/tests/json.rs
Fixes #223.
I left `into_span` so that this change is backwards compatible. `into_span` is now implemented in terms of `as_span` because they do the same thing.
Since the two methods are mostly the same, the test is also pretty much exactly the same. I added an extra part at the end to make sure that the pair is not consumed by the method.
=> Created as_span method

pest/src/parser_state.rs, pest/src/stack.rs, vm/src/lib.rs
I actually also discovered a subtle bug. Originally, the stack would never be restored to an empty state since snapshotting requires that the ops vec was modified at least once prior to snapshot. To fix this, I pre-seed the snapshots with 0
=> Added a docstring and example to restore_on_err

derive/src/generator.rs, pest/examples/parens.rs, pest/src/error.rs, pest/src/lib.rs, pest/src/macros.rs, pest/src/parser_state.rs, pest/tests/calculator.rs, pest/tests/json.rs, vm/src/lib.rs, vm/src/macros.rs
The former `Error` type kept reference to the input. This meant that it was impossible for an Error to be fully owned, resulting in a hard-to-use type that was incompatible with failure. This commit Refactors the error code, implements a friendlier API, promotes error to a public mod, and transforms `Error` into an owned type. Fixes #204.
=> Refactored Error.

README.md, pest_derive/Cargo.toml, pest_grammars/Cargo.toml
In testing [`criterion` with Cargos `-Z minimal-versions`](https://github.com/japaric/criterion.rs/issues/183) I notestd that `pest_derive` does not work with quote = "<=0.3.14". This PR bumps the minimal acceptable versions in Cargo.toml to 0.3.15, so as to match what you are really compatible with.
This gets `pest.*` working with Cargos -Z minimal-versions. This is part of the process of seeing how hard minimal-versions is for crates to use in preparation for getting it stabilized for use in CI. It is easy to use if all of your dependencies support it, but much harder if trying to impose it on them.
=> pest_derive does not work with quote = "0.3.14" so bump dep

derive/tests/lists.pest, derive/tests/lists.rs
For now, this grammar can live as an integration test in `pest_derive` until a better, more involved example will be created.
=> Added a simple indentation grammar.

derive/src/generator.rs, derive/src/macros.rs, meta/src/validator.rs
skip was reserved as a keyword due to an implementation detail. This new approach circumvents this need and permits its use as a rule.
=> Removed skip from pest_keywords.

derive/src/generator.rs, derive/tests/grammar.pest, derive/tests/grammar.rs, pest/src/unicode/mod.rs, vm/src/lib.rs, vm/src/macros.rs, vm/tests/grammar.pest, vm/tests/grammar.rs, vm/tests/lists.pest, vm/tests/lists.rs, vm/tests/reporting.pest
Brought `pest_vm` to parity with `pest_derive` and other fixes.
Should have tests in `grammar.pest` for all builtins.
=> pest_vm fixes

pest/src/parser_state.rs, pest/src/position.rs
The skip optimization was wrongly failing when the search patterns were not found before the end of input.
=> Fixed an optiomization bug.

.cargo/config, .travis.yml, Cargo.toml, bootstrap/Cargo.toml, bootstrap/src/main.rs, meta/.gitignore, meta/build.rs, meta/src/grammar.pest, meta/src/lib.rs, meta/src/parser.rs, meta/src/validator.rs
Does the minimum amount to get `pest_meta` compiling against pest:2.0.
Run `cargo bootstrap` to regenerate `meta/grammar.rs` from `meta/grammar.pest`.
The bootstrap generated `.rs` is included so that downstream users don't have to bootstrap compile the pest grammar, thus the bootstrap recursion is broken.
Closes #288
=> Bootstrap pest_meta with pest:2.0

.bors.toml, .travis.yml
https://bors.tech/
Requires the bors integration to have access to the organization to do its work; I've requested permission on its behalf. This is merely a suggestion, but I've had great success using bors on personal projects even without multiple PRs in flight at the same time, even just as a merge-when-green bot.
=> Set up bors-ng 

meta/Cargo.toml, meta/LICENSE-APACHE, meta/LICENSE-MIT
The README is nice to have, and LICENSE-APACHE might not be strictly required,
but LICENSE-MIT requires that it "shall be included".
=> meta: include README and LICENSE files in the package

pest/src/iterators/pairs.rs
How does `next_back` work? Would a `peek_back` be useful to have (for completeness?)?
=> Pairs::peek

generator/src/generator.rs
The conditional was probably added because it was in the original
hint to do this manually in the documentation.  There doesn't seem
to be a downside since the constant will be thrown away in any
case, being unused.
Fixes #320.
=> Generate dummy grammar include in release mode too.

meta/src/parser.rs, pest/src/parser_state.rs
Attempt positions values were incorrectly computed which led to error reporting inconsistencies in remote cases.
=> Fixed error reporting bug.

pest/src/parser_state.rs
=> Fix 'access to extern crates through prelude' compile error

.travis.yml, rustfmt.toml
This PR has been limited to the Travis matrix update, with most jobs allowed to fail temporarily.
I will resubmit the fmt, clippy, and misc. test improvements changes removed from this PR momentarily as a new PR.
-----
Original text:
Closes #294, closes #295, supersedes #310
This has a rather large diff since I did a `cargo fmt` across the whole workspace, but it should enable mindless rustfmt from here on. I can tweak the `rustfmt.toml` as well if there are other [configurations](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md) we want to change; I've deliberately pinned rustfmt to a nightly version.
Clippy is pinned to 1.29.0 as that's the first rust toolchain to contain clippy-preview. As we'd like to take advantage of the new edition eventually, #300, I'm …
=> New Travis matrix

.travis.yml
It wasn't set up completely correctly to begin with:
- `cargo install` failed if it had been cashed
- `tarpaulin`'s clean step kills the bootstrap executable if we let it
=> Fix coverage job

pest/src/error.rs, pest/src/lib.rs, pest/src/position.rs, pest/src/span.rs
I had to add an API for moving a position back.
An alternative would have been to modify `skip_while` to take a slice of `std::str::pattern::Pattern`s instead of `&[&str]` and add a `skip_back_while` function that does the same but backwards. Then we could have skipped back until we hit a non-newline character.
Should I do that instead?
Fixes #348
=> Fix error display if pos is after \n

.travis.yml, bootstrap/Cargo.toml
Bump bootstrap to use generator:2.0.1 and stop allowing failures for the minimum-versions CI job.
Merge once generator:2.0.1 is published.
=> Enforce minimal versions CI gate

README.md
The readme file contained calls to ['Pair::into_span'](https://docs.rs/pest/2.1.0/pest/iterators/struct.Pair.html#method.into_span), witch were deprecated in 2.0.0.
I have replaced calls to ['into_span'](https://docs.rs/pest/2.1.0/pest/iterators/struct.Pair.html#method.into_span) with ['as_span'](https://docs.rs/pest/2.1.0/pest/iterators/struct.Pair.html#method.as_span), as well as calling ['pair::as_str'](https://docs.rs/pest/2.1.0/pest/iterators/struct.Pair.html#method.as_str) directly instead of the ['span::as_str'](https://docs.rs/pest/2.1.0/pest/struct.Span.html#method.as_str).
This is my first pull request to any open source project. So I hope I've done this right :sweat_smile:
=> Removing deprecated method calls from README

pest/src/iterators/pair.rs
[Mentioned in the gitter channel](https://gitter.im/pest-parser/pest?at=5be61fe87326df140ee00980), `PrecClimber` hands outs `Pair` (as it should) and `FromPest` (in [pest-parser/ast](https://github.com/pest-parser/ast)'s `from-pest`) takes `&mut Pairs`.
This causes a problem where the current `from-pest` design (taking a mutable iterator cursor) isn't compatible with using a `PrecClimber`.
This patch gives `Pairs` the equivalent of `iter::once`, creating an iterator of a single `Pair` from said `Pair`. This makes it possible to then hand this new iterator to the `FromPest` implementation.
=> Add conversion Pair -> Pairs (iter::once)

pest/Cargo.toml, pest/src/iterators/pair.rs, pest/src/iterators/pairs.rs, pest/src/lib.rs
Closes #377
Implements the `to_json` function for both `Pair` and `Pairs` which generates a pretty-printed JSON that contains their information.
I followed the sketch given in #377, but I wonder if instead of `"pos": [start, end]` it would be better to have `"start"` and `"end"` as separate fields, as in pretty-printed format I personally find it easier to read with less nesting.
This is the generated string right now:
```
{
"pos": [
0,
5
],
"pairs": [
{
"pos": [
0,
3
],
"rule": "a",
"inner": {
"pos": [
1,
2
],
"pairs": [
{
"pos": [
1,
2
],
"rule": "b",
"inner": "b"
}
]
}
},
{
"pos": [
4,
5
],
"rule": "c",
"inner": "e"
}
]
}
```
This would be with `"start"` and `"end"`:
```
{
"start": 0,
"end": 5,
"pairs": [
{
"start": 0,
"end": 3,
"rule": "a",
"inner": {
"start": 1,
"end": 2,
"pairs": [ …
```
=> Generate lexical information of `Pair` and `Pairs` as JSON

pest/src/iterators/pairs.rs
Fixes issue https://github.com/pest-parser/pest/issues/401.
Sidenote: you have a multitude of failing tests on win10 nightly compiler, I don't know if you're aware.
=> Check if start < end in Pair::as_str

meta/Cargo.toml
I'm currently working on a no_std project that uses Pest in a proc macro, and also uses sha1 somewhere else in the crate graph. It uses sha1 in nostd mode. But because cargo ~~sucks~~ has [some really broken behavior](https://github.com/rust-lang/cargo/issues/4866) around build and dev dependencies, pest ends up activating the std feature for my build.
Pest doesn't really need the std feature of SHA-1 anyways. So this PR disables it.
=> Don't enable std feature on sha-1

bootstrap/Cargo.toml
bootstrap failed to build because it was depending on an older version of the generator. Fixes #424.
=> Fixed build.

.travis.yml, README.md, fuzzit.sh
Hi guys. Really nice how you have some fuzz targets. What about running them automatically on Fuzzit?
This patch sets it up. All 3 targets are fuzzed. There's a [successful run](https://travis-ci.org/bookmoons/pest/builds/577269637) under my Travis account.
The PR build will fail due to missing an API key. Setup is like this:
* In [Fuzzit](https://fuzzit.dev/) create the targets `pest-parse` `pest-toml` `pest-json`.
* In Fuzzit settings grab an API key. In repo settings in [Travis](https://travis-ci.org/) paste it to `FUZZIT_API_KEY`.
=> Automated fuzzing

generator/src/generator.rs, generator/src/macros.rs
There is a lot of value in outputs produced by compilers being
reproducible. Rust makes it somewhat hard to get it right, but most of
the time rustc’s outputs are also reproducible. This allows us to enjoy
all the benefits as other more primitive toolchains. Most of the time.
Pest was, sadly, one of those examples where reproducibility was not a
concern and HashMap was used to implement some of the  code generation
portions. Replacing this `HashMap` with a `Vec` and a `O(nm)` loop is
the easy solution. With the values that `n` and `m` get substituted with
in practice, however, this loop should still be approximately as good as
the previous `HashMap` implementation.
=> Remove HashMap from derive/generate

pest/src/prec_climber.rs
I'm really sorry for not catching this earlier, I assumed they were not considered globals by the linter when enclosed in their own scope and the doctest doesn't seem to emit any warnings for me, I even tried denying all warnings for it. Now I tested it in a real project and all of my tests there work as expected without any warnings.
=> Silence non_upper_case_globals warnings

generator/src/generator.rs
In situations where `CARGO_MANIFEST_DIR` is set atypically, pest can break it's grammar file finding
=> Makes include_str! use a relative path

pest/src/error.rs
Adds the ability to get the message from an `ErrorVariant`
`message` method on `ErrorVariant` returns a `Cow<str>` to save an allocation on peeking message on `ErrorVariant::CustomError`
fixes #365
=> adds message method to ErrorVariant

pest/src/error.rs
PR #454 broke the build by adding a doctest that doesn't compile, in particular it gave the following error:
```
failures:
---- src/error.rs - error::ErrorVariant<R>::message (line 445) stdout ----
error[E0282]: type annotations needed for `pest::error::ErrorVariant<R>`
--> src/error.rs:447:15
|
5 | let variant = ErrorVariant::CustomError {
|     -------   ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `R` declared on the enum `ErrorVariant`
|     |
|     consider giving `variant` the explicit type `pest::error::ErrorVariant<R>`, where the type parameter `R` is specified
error: aborting due to previous error
For more information about this error, try `rustc --explain E0282`.
Couldn't compile the test.
failures:
src/error.rs - error::ErrorVariant<R>::message (line 445)
test …
```
=> Fix build after PR #454

.travis.yml
cc @SkiFire13 
We've never promised MSRV support, and the "minimal versions" build is just to make sure that our toml is actually requesting a version that we build on. So because of this, I'm just bumping the arbitrary nightly to a later arbitrary nightly (that hopefully is somewhat recent enough?); specifically, ~~I bumped the version by just under a year, so it's again about a year back from current~~.
Hopefully this fixes the build.
bors: r+
=> Bump minimal-versions test version

pest/src/macros.rs
Using pest macros (in my case, `parses_to`) I get a [warning](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/non_fmt_panic/index.html) from the compiler.
This change rewrites slightly the macro panics to make the warnings go away.
=> Remove lint warning in macros

pest/src/error.rs
Hi, I noticed there is currently no way to get the path set using `with_path` from `Error`. This short PR adds a function to get a reference to the currently set path.
My use case for this: I process a bunch of files and collect all parsing errors, then I'd like to filter and group them by the file that caused them. At the moment, I have the possibility to just get the location within the file, but not the path itself, because it is not public. I couldn't find a viable alternative to accomplish this.
Thank you for the great library!
Nico
=> Add a function to retrieve the path from the Error struct

pest/src/position.rs, pest/src/span.rs
I would be very nice if these types were `Copy`.
If they are not `Copy` for a reason (which I assume has to do with future-proofing), then go ahead and close this.
=> implement Copy for Position and Span

README.md
https://github.com/huacnlee/autocorrect
AutoCorrect has used Pest as language parser, there has 20 languages support (Just implemented Comment, String support).
https://github.com/huacnlee/autocorrect/tree/main/src/lib/grammar
=> Add project using pest

generator/src/generator.rs, generator/src/lib.rs
Pest needs the full path with CARGO_MANIFEST_DIR to read the grammar
file, but when emitting `include_str!` the original path (relative to
the Rust source file) should be used.
=> Use the source-relative path in include_str!

README.md
Project: yaml-peg
Description: PEG parser for YAML written in Rust
Repo: https://github.com/aofdev/yaml-peg
**Grammar pest:** https://github.com/aofdev/yaml-peg/blob/main/src/parser/grammar/yaml.pest
=> Add yaml-peg to projects using Pest

meta/Cargo.toml, meta/src/lib.rs
Hi,
I was trying to get my rust project to build on a M1 mac and maplit was breaking my build.
From what I can see maplit is not used, so I removed it.
=> removed unused maplit

pest/Cargo.toml
Previously, the std feature for ucd-trie was enabled by default, which was preventing builds in no_std environments. This PR only enables the std feature when std is selected for pest.
=> Don't enable "std" for ucd-trie when std not selected

README.md, bootstrap/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, vm/Cargo.toml
- Remove deprecated Travis-CI status badge from main README.md and use current GitHub action based CI badge to show current build/CI status on default branch
- Remove links under Cargo.toml `badge` section since this functionality has been deprecated and removed - [Reference](https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section)
=> fix: Remove deprecated Travis-CI links and deprecated `badges` section

.gitpod.yml, CONTRIBUTING.md
[Gitpod](https://gitpod.io) is a really cool tool and integrating with pest would be nice.
=> Add Gitpod config

pest/src/error.rs, pest/src/position.rs
`new_from_pos` and `new_from_span` only visualize newline
characters if positions point to the newline characters.
=> fix: Limit error messages new line visualization (fixes #362)

pest/Cargo.toml, pest/src/error.rs
In an effort to update this crate, I have migrated the `error` module of `pest` to `thiserror`. This removes some boilerplate impls, and makes its errors compatible with some other error reporting tools.
=> Migrate to `thiserror`

.github/workflows/ci.yml, bootstrap/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, grammars/benches/json.rs, grammars/fuzz/Cargo.toml, meta/Cargo.toml, meta/fuzz/Cargo.toml, meta/src/validator.rs, pest/Cargo.toml, pest/src/error.rs, pest/src/lib.rs, pest/src/parser_state.rs, vm/Cargo.toml
as per https://github.com/pest-parser/pest/pull/615#issuecomment-1179755352
besides criterion, it is now possible to compile the
`const_prec_climber` feature on stable, because
`const_fn_trait_bound` was stabilized
=> chore: switch benches to criterion plus MSRV bump to 1.56

.github/workflows/release.yml, derive/Cargo.toml, generator/Cargo.toml, generator/src/generator.rs, generator/src/lib.rs, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, vm/Cargo.toml
closes https://github.com/pest-parser/pest/issues/672
+ bumped version numbers and split up the release flow as a workaround for a bug in katyo/publish-crates GH action
=> fix: undo https://github.com/pest-parser/pest/pull/522

pest/Cargo.toml, pest/src/span.rs
Partially revives #456 and merge would partially close #455.
This implementation changes the name of the new feature in #456 from `Span::sub_span` to `Span::get` to have parity with `str::get`.
This implementation does not require `std`.
=> Implement `Span::get`

pest/src/lib.rs, pest/src/span.rs
The other half of closing #455 #456.
=> Add `Span::lines_span()`

CONTRIBUTING.md, README.md, derive/src/lib.rs
Found via `codespell -L crate,ser,complies`.
=> doc: fix typos

pest/src/error.rs
Fixes #693. Let's see what's wrong with the simple fix.
=> Remove trait bound from Error type

.github/workflows/release.yml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, release.sh, vm/Cargo.toml
added a custom release bash script, because the previous GH action
failed at different stages, so a part of it needed to be published
manually. we'll see if this works this time.
=> ci: release 2.3.0

derive/tests/grammar.rs, generator/src/lib.rs
This is a proposeal to fix #325.
The new logic looks for the `[grammar = "$path"]` path in `CARGO_MANIFEST_DIR/` before using the fallback of `CARGO_MANIFEST_DIR/src`.
This allows projects that don't have a `src` folder to use a grammar file, while staying backward compatible.
**Alternative implementation approach:**
One could theoretically use the [absolute](https://doc.rust-lang.org/std/path/fn.absolute.html) function.
Sadly, this function is still nightly, which makes this approach unfeasible.
**Current workarounds:**
- Restructure the project so it has a `src` folder
- Create a stub `src` folder, so one can use relative paths
- Inline all of the grammar via `grammar_inline`
=> fix: Search for grammar file from CARGO_MANIFEST_DIR

.github/actions/setup/action.yml, .github/workflows/ci.yml, .github/workflows/release.yml, generator/src/lib.rs, release.sh, semvercheck.sh
=> ci: better CI hygiene

derive/Cargo.toml, derive/examples/calc.pest, derive/examples/calc.rs, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, meta/src/parser.rs, meta/src/validator.rs, pest/Cargo.toml, pest/src/lib.rs, pest/src/pratt_parser.rs, pest/tests/calculator.rs, vm/Cargo.toml
Closes #461
based on #344
Co-authored-by: @segeljakt
=> feature: unary prefix/suffix operator support via PrattParser

generator/src/lib.rs, meta/src/parser.rs, pest/src/error.rs, pest/src/parser.rs, pest/src/parser_state.rs, pest/src/position.rs, vm/src/lib.rs
code was fixed where possible;
elsewhere it'd need API-breaking changes,
so it was just annotated to allow that for now.
=> chore: clippy fixes and ignores

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where pest already runs. CIFuzz can help detect regressions and catch fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
=> ci: add CIFuzz GitHub action

Cargo.toml, codecov.yml, debugger/Cargo.toml, debugger/_README.md, debugger/src/lib.rs, debugger/src/main.rs, derive/Cargo.toml, generator/Cargo.toml, generator/src/lib.rs, grammars/Cargo.toml, meta/Cargo.toml, meta/src/lib.rs, meta/src/parser.rs, meta/src/validator.rs, pest/Cargo.toml, release.sh, vm/Cargo.toml, vm/src/lib.rs
based on the old PR by @dragostis: https://github.com/pest-parser/pest/pull/277
Changes that were made:
- debugger core context was refactored and extracted to a lib (so that it could be used in other frontends, e.g. editor plugins)
- CLI was extended using rustyline helpers to provide file completions, history etc.
- applied suggestions from @hansihe from the old PR (https://github.com/pest-parser/pest/pull/277#issuecomment-421838669):
1. added `ba` (add breakpoints at all rules) which is useful for stepping through the entire grammar, plus breakpoint deletions and loading input directly from readline;
2. added command line arguments.
- changed the listener function to return a boolean, so that the debugger can signal back to a parsing thread to finish before reaching its input's EOF.
=> feature: added a `pest_debugger` crate (fixes #98)

debugger/src/main.rs
Fixes a panic when you provide the debugger executable with an argument it does not expect. It now exits gracefully.
before:
```
$ pest_debugger random args
thread 'main' panicked at 'internal error: entered unreachable code', /home/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/pest_debugger-2.5.0/src/main.rs:259:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
after:
```
$ pest_debugger random args
Error: unexpected argument `random`
Error: unexpected argument `args`
```
=> Fix unexpected argument panic in `pest_debugger`

derive/src/lib.rs, pest/src/lib.rs
Example borrowed and adapted from #742
=> doc: explain that matching is greedy without backtracking

debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, pest/src/position.rs, vm/Cargo.toml
it was put under the "memchr" feature-flag, as memchr SIMD support is only on x86_64 at the moment (json bench is ~8% faster over baseline there): https://github.com/pest-parser/pest/pull/737#issuecomment-1325784358 once memchr has the Arm SIMD support, this could be perhaps the default implementation.
For Aho-Corasick, it'll require more investigation.
=> perf: add a faster skip_until using SIMD memchr

generator/src/generator.rs, meta/src/validator.rs, vm/src/lib.rs
This prefixes all non-builtin rules with `r#` to allow for use of rust keywords as pest rules. This is my first pull request so please let me know if I should make any changes.
This refactors code to use [`format_ident!`](https://docs.rs/quote/latest/quote/macro.format_ident.html) rather than `Ident::new` (with `format!` internally in the case of `_PEST_GRAMMAR_{}`), as it works the same internally, with the `Span` falling back to `Span::call_site()` when not given an `Ident`, so there shouldn't be any issues.
Updated test cases that use identifiers as expressions to test escaping them
Fixes #747
=> Allow use of rust keywords as pest rules

grammars/benches/json.rs, pest/src/iterators/flat_pairs.rs, pest/src/iterators/pair.rs, pest/src/iterators/pairs.rs, pest/src/lib.rs, pest/src/macros.rs, pest/src/position.rs
ref: #707, #560
This implementation is based by I use in AutoCorrect: https://github.com/huacnlee/autocorrect/blob/v2.5.5/autocorrect/src/result.rs#L267
```rust
let mut pairs = JSONParser::parse(Rule::a, "....").unwrap();
let pair = pairs.next().unwrap();
let (line, col) = pair.line_col()
```
In this method, line, col has managed by move_cursor on Pairs iterator `next` method. For a large input string this method will be faster, because it does not need to re-calculate all of the input string. The line, col value has been cached in the pair and accumulate by `next` method.
And I keep the old `line_col` method in `Position` struct, because I found that has been used in other without `Pairs` iterator. This method still works, but it will be slower than the new method.
```
pair.line_col …
```
=> Improve line, col calculate performance by use move cursor on Pairs Iterator.

derive/examples/base.pest, derive/examples/calc.pest, derive/examples/calc.rs, generator/src/lib.rs
Resolve #197 #333
Example:
```rust
#[derive(Parser)]
#[grammar = "base.pest"]
#[grammar = "json.pest"]
pub struct JSONParser;
```
By this changes, we can split the sharing rules in to a single file, and then load it for other grammar files.
In my AutoCorrect case, this will useful, because there have so many duplicate rules (e.g. `space`, `comment`, `newline`) defined in each grammars.
https://github.com/huacnlee/autocorrect/tree/v2.5.5/autocorrect/grammar
=> Add to support load multiple grammars for derive generator. 

meta/Cargo.toml, meta/build.rs
I submitted an issue (#763) about the problems depending on SHA1 is causing with some build systems and security.  This PR  removes the SHA1 library and replaces it with the SHA2 library.
I'm not sure what side effects this will have on the build though.  The change is in meta/build.rs, and it looks like SHA1 is only being used to name a grammar file that gets downloaded and compared before deciding to create a new grammar file.  This change would definitely cause that step to happen with the first new build after merge.
=> #763 Switches SHA1 for SHA2

debugger/Cargo.toml, derive/Cargo.toml, derive/tests/implicit.pest, derive/tests/implicit.rs, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, meta/src/optimizer/factorizer.rs, meta/src/optimizer/mod.rs, pest/Cargo.toml, vm/Cargo.toml
closes #762
the full fix would require a bigger overhaul / refactoring of the optimizer
=> fix: restrict the factorizer case to only atomic and compoundatomic rules

.github/workflows/ci.yml, .github/workflows/release.yml
https://github.com/pest-parser/pest/actions/runs/3946148398/jobs/6753649401
Ref:
- https://github.com/kkawakam/rustyline/compare/v10.0.0...v10.1.0
- https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1620-2022-06-30
- https://github.com/rust-lang/rust/pull/94457
=> CI use Rust 1.62.0 for fix rustyline 10.1.0 `#[default]` compile error.

debugger/src/main.rs
0_o, silly little typo swapped the `ba` and `da` commands in the debugger.
=> fix: typo in pest_debugger

debugger/Cargo.toml, debugger/src/main.rs
This PR adds a simple synchronous update checker for pest_debugger. If an update is found, the new version is printed to the console:
`A new version of pest_debugger is available: v3.9.4` 
Else, 
`pest_debugger is up to date`
is printed.
The implementation discards any errors that occur during update checking since the user doesn't really need to know about them - update checking is non-essential. It's using the crates.io API, which is subject to their [policies](https://crates.io/policies). From what I understand, making one request every time someone starts pest_debugger will be fine.
Open for any feedback, my first contribution to an open source Rust project.
=> Feature: Simple update checker for pest_debugger

grammars/benches/json.rs, grammars/tests/examples.json, grammars/tests/examples.line-col.txt, grammars/tests/json.rs, pest/src/iterators/flat_pairs.rs, pest/src/iterators/line_index.rs, pest/src/iterators/mod.rs, pest/src/iterators/pair.rs, pest/src/iterators/pairs.rs, pest/src/parser_state.rs
Add `LineIndex` instead of `Pairs::move_cursor` for improve Pairs iterate and `Pair::line_col` performance.
Resolve #784
Ref: https://github.com/rust-lang/rust/blob/1.67.0/src/tools/rust-analyzer/crates/ide-db/src/line_index.rs
Benchmark result:
> (Updated on 2022.02.02 18:00) After I fix to for support utf-8, the new `line-index` implementation of line_col benchmark result is close to `fast-line-col`.
> But when In a last file, `line-index` will faster. 
Benchmark file: https://github.com/pest-parser/pest/blob/16de4fa29228ab07a8c49279de6c5f9814496ed6/grammars/benches/json.rs
```
// With 500 times iter
pair.line_col (with LineIndex)               time:   [22.426 µs 22.489 µs 22.556 µs]
position.line_col                            time:   [212.59 µs 213.38 µs 214.29 µs]
position.line_col …
```
=> Add `LineIndex` instead of `Pairs::move_cursor` for improve `Pairs::next` and `Pair::line_col` performance.

debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, meta/src/ast.rs, meta/src/grammar.pest, meta/src/optimizer/mod.rs, pest/Cargo.toml, pest/src/position.rs, vm/Cargo.toml
using line_col from pairs is recommended: https://github.com/pest-parser/pest/pull/785#issuecomment-1413604569 as it's faster or similar performance after the line-index patch
=> chore: added docs for semver changes in grammar + remove fast-col-line

grammars/src/grammars/json.pest, meta/src/grammar.pest
=> Fix grammar `////` parsing error.

README.md, debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, pest/Cargo.toml, vm/Cargo.toml
ref: https://github.com/pest-parser/pest/issues/795#issuecomment-1454494160
=> doc: added a note regarding the no_std support

pest/src/pratt_parser.rs
Currently the typings require the passed in callbacks to have the lifetime `'i`, and thus any values it reference must also have the same lifetime. If these callbacks return a value with lifetime `'i`, the borrow checker incorrectly assumes that those referenced values must also outlive the return value.
For example this code:
```rust
fn test_pratt<'a>(pairs: Pairs<'a, Rule>, message: &str) -> &'a str {
PRATT_PARSER
.map_primary(|pair| {
// println!("{message}");
pair.as_str()
})
.map_infix(|lhs, pair, rhs| {
println!("{message}");
pair.as_str()
})
.parse(pairs)
}
```
fails to compile with this error:
```
error[E0621]: explicit lifetime required in the type of `message`
--> src/compiler/expression.rs:285:5
|
284 |   fn test_pratt<'a>(pairs: Pairs<'a, Rule>, message: &str) -> &'a str {
| …
```
=> Fixup lifetimes of PrattParser

generator/Cargo.toml, generator/src/lib.rs
Just fixes up the breakages from the `syn` update
It seems like the only thing that needed changing was from `meta` becoming a field of `Attribute` with nested meta parsing getting moved to a separate method entirely
=> Update syn to v2

grammars/benches/json.rs, pest/src/iterators/flat_pairs.rs, pest/src/iterators/pairs.rs, pest/src/iterators/tokens.rs, pest/src/span.rs
PR adds impl `ExactSizeIterator` and `size_hint` accordingly for `Pairs`, `Tokens`, `FlatPairs` and `LinesSpan`. This can hint rust compiler to allocate proper memory amount while collecting to vector or similar containers
=> Implement `ExactSizeIterator` for `Pair` iterators

meta/src/validator.rs
Fixes #830 #571
The bugs up there are now fixed. But new were found.
The first change I made was fixing a typo [at this line](https://github.com/pest-parser/pest/blob/6355eaec4e71ed223f6f77c8095f52d7fea349b1/meta/src/validator.rs#L240):
```rust
if ident == "soi" || ident == "eoi" { => if ident == "SOI" || ident == "EOI" {
```
Since the keywords are the uppercase ones, and that I don't think keywords are case insensitive, this was only a typo. But I'm not sure about that.
Since [`pest_meta::validator::is_non_failing`](https://github.com/pest-parser/pest/blob/6355eaec4e71ed223f6f77c8095f52d7fea349b1/meta/src/validator.rs#L270) and [`pest_meta::validator::is_non_progressing`](https://github.com/pest-parser/pest/blob/6355eaec4e71ed223f6f77c8095f52d7fea349b1/meta/src/validator.rs#L232) are …
=> Mitigate errors in reporting grammars that can cause the parser to run indefinetely

meta/src/ast.rs, meta/src/optimizer/concatenator.rs, meta/src/optimizer/factorizer.rs, meta/src/optimizer/lister.rs, meta/src/optimizer/mod.rs, meta/src/optimizer/rotater.rs, meta/src/optimizer/skipper.rs, meta/src/parser.rs
I removed the multiple TODO comments about Rust's box syntax, because it has been removed according to rust-lang/rust/pull/108471
=> Removed TODO about removed box syntax

derive/examples/help-menu.pest, derive/examples/help-menu.rs
For `pest_derive`, an example program is added here which parses a common help menu format and dumps a part of the parse tree to stdout.
=> derive/examples: add a help menu grammar and parser

pest/src/error.rs
Adds `From<Position<'_>>` and `From<Span<'_>>` implementations to `LineColLocation`.
This will make integrating Pest errors and types into custom error types slightly less verbose.
It's technically possible to create a pest error from a span and then get the LCL from that, but it's an unnecessary overhead.
=> feat: add simple Position/Span From implementations for LineColLocation

derive/examples/calc.rs, pest/src/pratt_parser.rs
Change `calc` example's behavior from
```
> -10!
-10! => ((-10)!) => 1
```
to
```
> -10!
-10! => (-(10!)) => -3628800
```
In my defense:
* [Google](https://www.google.ru/search?q=-10%21)
* [WolframAlpha](https://www.wolframalpha.com/input?i=-10%21)
* [The rust-analyzer guy](https://matklad.github.io/2020/04/13/simple-but-powerful-pratt-parsing.html):
> Well, let’s add `!` for factorials. It should bind tighter than `-`, because `-(92!)` is obviously more useful than `(-92)!`.
* The calculator in the start menu of my KDE Plasma:
all share the same sentiment. That is, `-10! = -(10!)`
=> Swap precedence of negation and factorial

.github/workflows/ci.yml, bootstrap/Cargo.toml, bootstrap/src/main.rs, debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, grammars/src/lib.rs, meta/Cargo.toml, meta/build.rs, meta/src/parser.rs, pest/Cargo.toml, vm/Cargo.toml
Based on #495
Use cargo to run the bootstrapper.
The default feature was flipped compared to #495,
so that the existing CI workflows continue working as before.
The projects that want to depend on git-based pest can do as follows:
`pest_derive = { git = "...", features = ["not-bootstrap-in-src"] }`
=> Conditional source-tree bootstrapping

.github/workflows/ci.yml, debugger/Cargo.toml, derive/Cargo.toml, derive/tests/implicit.rs, generator/Cargo.toml, generator/src/generator.rs, grammars/Cargo.toml, meta/Cargo.toml, meta/src/ast.rs, meta/src/optimizer/mod.rs, meta/src/parser.rs, meta/src/validator.rs, pest/Cargo.toml, release.sh, semvercheck.sh, vm/Cargo.toml, vm/src/lib.rs
this is to address potential semver issues due to Cargo dependency intermixing, see: https://github.com/pest-parser/pest/issues/849
So, for existing users who depend on 2.X in the dependency tree, 2.7.0 pest-meta should work with 2.5.6 and below pest-generator etc. People who need the new grammar features can do so by specifying the `grammar-extras` feature in Cargo.toml:
```
...
pest_derive = {version = "2.7", features = ["grammar-extras"]}
```
=> feature-guard the new grammar features with "grammar-extras"

README.md
A library that uses a JSON5 Pest grammar to parse JSON5 into "nodes" that include the location of the JSON element in the original text.
=> Add reference to json5-nodes

README.md, debugger/Cargo.toml, derive/Cargo.toml, derive/tests/oneormore.pest, derive/tests/oneormore.rs, generator/Cargo.toml, generator/src/generator.rs, grammars/Cargo.toml, meta/Cargo.toml, meta/src/optimizer/mod.rs, meta/src/optimizer/unroller.rs, pest/Cargo.toml, vm/Cargo.toml, vm/src/lib.rs
the fix was feature-guarded with "grammar-extras" in order to keep the semver compatibility. plus a test was added.
Closes #396
=> one-or-more rule fix based on #397

grammars/src/grammars/json.pest
JSON documents don't require being rooted at an object or an array
=> Make the root a value.

pest/src/lib.rs, pest/src/span.rs
Hello Pest team!
I'm working on a Ctiny language interpreter for a university course. You can find my repository [here | GitHub](https://github.com/0nyr/ctiny_interpreter).
While working on the AST, I have faced a problem.
Considering the following grammar:
```
expression = { disjunction } // top level expression is disjunction
disjunction = { conjunction ~ (disjunction_operator ~ conjunction)* }
conjunction = { equality ~ (conjunction_operator ~ equality)* }
equality = { relation ~ (equality_operator ~ relation)* }
relation = { addition ~ (relation_operator ~ addition)? }
addition = { term ~ (addition_operator ~ term)* }
term = { factor ~ (multiplication_operator ~ factor)* }
factor = { unary_operator? ~ primary }
```
and my AST node structs:
```
// Base AST node
#[derive(Debug, …
```
=> Merging Spans :recycle: 

pest/src/iterators/pair.rs, pest/src/iterators/pairs.rs, pest/src/lib.rs, pest/src/span.rs
Hello Pest team.
This PR is a followup to my last PR [Merging Spans :recycle: #887](https://github.com/pest-parser/pest/pull/887#issue-1805224983).
In this last PR, I have introduced a getter for `Span` in order to be able to access the private `input` field of a `Span`. This allows to access the original input string without having to pass its reference everywhere in function arguments. In my personal project, I use this feature to be able to merge `Span`s.
There is no reason not to add this function to other types that also have this private field and a public `as_str()` function. I have added meaningful doc and tests and run `cargo fmt`.
I also renamed my tests to all have different names, making test debugging via commands like `cargo test <get_input_test> -- --nocapture` …
=> Adding get_input() to types that already have public as_str() 🏷️

meta/src/ast.rs, meta/src/optimizer/mod.rs
Non-related changes included in previous pull request #895.
Improve the implementation added in #889.
Corresponding tests added.
=> Implement Display for Expr and OptimizedExpr

generator/src/generator.rs
The generator currently wraps tags in an instance of `alloc::borrow::Cow`. This PR changes that to `std::borrow::Cow` conditional on the `std` feature flag being active.
Closes #899.
=> Add feature gated `Cow` module paths

pest/src/parser_state.rs
`intepreted` -> `interpreted`
It may be a good idea to include [crates-ci/typos](https://github.com/crate-ci/typos), but it seems to throw a lot of false positives here.
=> docs: fix small typo in `match_range`

pest/Cargo.toml, pest/benches/stack.rs, pest/src/lib.rs, pest/src/stack.rs
Hello, I've noticed that the previous Stack will maintain the log of every push and pop after the snapshot is taken, and I think some of them are not necessary.
I implement a new version of Stack, and only pop operations on those elements that come from previous state will be logged. I didn't change the Stack's interface, but I have to make the Stack public for the benchmark.
I use Criterion for benchmark, and it shows that there is a performance improvement in all tested cases.
I've tested the stack with small, medium and large objects, and their sizes are 8, 24, 1024 respectively on my machine (Win10, AMD x64).
And I've tested four kinds of operations (Each for 10000 times):
- Take a snapshot, push an element, restore, push an element.
- Take a snapshot, push an element, clear the …
=> A new stack implementation that should be faster and less space-consuming

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.toml, debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, meta/Cargo.toml, meta/src/parser.rs, pest/Cargo.toml, pest/src/error.rs, pest/src/iterators/pairs.rs, pest/tests/calculator.rs, pest/tests/json.rs, vm/Cargo.toml
memchr now supports aarch64, so it's made default: https://github.com/BurntSushi/memchr/pull/129
cargo lib (used in the not-bootstrap-in-src feature) did not respect umask: https://github.com/advisories/GHSA-j3xp-wfr4-hx87
(probably not an issue here)
=> small cargo clippy fixes + dependency bumps

pest/src/iterators/pairs.rs
Clarify that the `Pairs::{find_tagged, find_first_tagged}` methods flatten the `Pairs` iterator
=> Add clarification to the docs

.github/actions/setup/action.yml, .github/workflows/ci.yml, README.md, bootstrap/Cargo.toml, debugger/Cargo.toml, derive/Cargo.toml, generator/Cargo.toml, grammars/Cargo.toml, grammars/fuzz/Cargo.toml, meta/Cargo.toml, meta/fuzz/Cargo.toml, pest/Cargo.toml, vm/Cargo.toml
memchr is now enabled by default and its latest version's MSRV is 1.61
=> bump MSRV to 1.61 (due to memchr's MSRV)

generator/src/generator.rs
This function returns all variants of the generated Rule so that they can be enumerated/searched for/etc. Also updated the tests to reflect the new output. 
The motivation for this is that I'd like to write a program to automatically verify some properties of the grammar that I'm working on, but the Rule type that is used by the generated parser is an enum. The Rust language doesn't provide any way to enumerate an enum unless you make a matching variable to hold all the variants and keep it in sync fastidiously (this kind of thing makes me tired and anxious). There are crates like strum that automate this, of course, but pest doesn't currently depend on any of those. 
This change just makes the generator also produce a function that returns a variable with all of the Rule variants. That …
=> Update pest_derive to generate a list of all rules in Rule::all_rules().

README.md
There is no need to use extern crates since rust 2018 so updating the documentation to prevent confusion among new learners of rust
=> Use Rust 2018 format for crates 
